# MATH 210 Introduction to Mathematical Computing

## November 4, 2019

* Eigenvalues and eigenvectors

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

We use the function `scipy.linalg.eig` to compute eigenvalues and eigenvectors of a matrix $A$.

In [2]:
A = np.array([[-1,4],[0,-2]])

In [3]:
result = la.eig(A)

The function returns a tuple.

In [4]:
type(result)

tuple

The first entry in the tuple is the array of eigenvalues.

In [5]:
result[0]

array([-1.+0.j, -2.+0.j])

The second entry in the matrix of unit eigenvectors.

In [6]:
result[1]

array([[ 1.        , -0.9701425 ],
       [ 0.        ,  0.24253563]])

Note:

1. `la.eig` returns a tuple consisting of 2 NumPy arrays.
2. The first array has the eigenvalues.
3. The second array is a matrix with corresponding eigenvectors in the columns.
4. Eigenvalues are returned as complex numbers even if they are real.
5. Eigenvectors are unit vectors $\| v \| = 1$.

If we know eigenvalues are real, we can use `numpy.real` to get the real part.

In [7]:
np.real(result[0])

array([-1., -2.])