# MATH 210 Introduction to Mathematical Computing

## October 28, 2019

* scipy.linalg
* Matrix multiplication
* Solving systems of equations
* Cayley-Hamilton Theorem

In [1]:
import numpy as np
import scipy.linalg as la

## scipy.linalg

Let's check out the [documentation](https://docs.scipy.org/doc/scipy/reference/linalg.html). We represent matrices as NumPy arrays.

In [2]:
M = np.array([[1,2],[3,4]])

In [3]:
print(M)

[[1 2]
 [3 4]]


Recall, the asterisk `*` is array multiplication: entry by entry multiplication.

In [4]:
M * M

array([[ 1,  4],
       [ 9, 16]])

Matrix multiplication is given by `@` symbol.

In [5]:
M@M

array([[ 7, 10],
       [15, 22]])

Unfortunately, there is no matrix power operation symbol like `^` in MATLAB.

Instead, there is a function we can use:

In [6]:
np.linalg.matrix_power?

In [7]:
from numpy.linalg import matrix_power as mpow

In [8]:
mpow(M,2)

array([[ 7, 10],
       [15, 22]])

The reason for this is that matrix multiplication is computationally expensive for big matrices. We need optimized functions such `matrix_power` to do it.

There are several functions for doing familiar linear algebra operations.

In [9]:
N = np.array([[3,2,1],[-1,1,0],[4,-2,1]])

In [10]:
print(N)

[[ 3  2  1]
 [-1  1  0]
 [ 4 -2  1]]


In [11]:
N@N

array([[11,  6,  4],
       [-4, -1, -1],
       [18,  4,  5]])

Compute the inverse:

In [12]:
Ninv = la.inv(N)

In [13]:
print(Ninv)

[[ 0.33333333 -1.33333333 -0.33333333]
 [ 0.33333333 -0.33333333 -0.33333333]
 [-0.66666667  4.66666667  1.66666667]]


Compute the determinant:

In [14]:
la.det(N)

3.0

In [15]:
la.det(M)

-2.0

Compute the tranpose:

In [16]:
N.T

array([[ 3, -1,  4],
       [ 2,  1, -2],
       [ 1,  0,  1]])

In [17]:
np.transpose(N)

array([[ 3, -1,  4],
       [ 2,  1, -2],
       [ 1,  0,  1]])

Solve a system of equation $Ax = b$

In [18]:
A = np.array([[0,1],[1,2]])
b = np.array([[2],[1]])
print(A)
print(b)

[[0 1]
 [1 2]]
[[2]
 [1]]


In [19]:
x = la.solve(A,b)

In [20]:
print(x)

[[-3.]
 [ 2.]]


Let's verify this is the solution:

In [21]:
A@x

array([[2.],
       [1.]])

We could also use the inverse to solve:

In [22]:
x = la.inv(A)@b

In [23]:
print(x)

[[-3.]
 [ 2.]]


This is usually a bad idea. Computing the inverse of a LARGE matrix is computationally expensive. The function `la.solve` is highly optimize to solve $Ax = b$ very quickly. Let's compare the two methods and see which one is faster.

In [32]:
N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

In [33]:
print(A.shape)
print(b.shape)

(1000, 1000)
(1000, 1)


In [34]:
%%timeit
x = la.solve(A,b)

2.19 s ± 365 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [35]:
%%timeit
x = la.inv(A)@b

2.86 s ± 330 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Example

Let's verify the [Cayley-Hamilton Theorem](https://en.wikipedia.org/wiki/Cayley–Hamilton_theorem) for some specific matrices.

For a 2 by 2 matrix, we can show

$$
p(\lambda) = \lambda^2 - \mathrm{tr}(A) \lambda + \mathrm{det}(A)
$$

In [36]:
A = np.array([[4,1],[-2,3]])
print(A)

[[ 4  1]
 [-2  3]]


In [37]:
np.trace(A)

7

In [38]:
la.det(A)

14.0

In [39]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [40]:
A@A - 7*A + 14*I

array([[0., 0.],
       [0., 0.]])

This works for every 2 by 2 matrix!

In [41]:
A = np.random.rand(2,2)
print(A)

[[0.69913711 0.81205851]
 [0.20267577 0.8249526 ]]


In [42]:
result = A@A - np.trace(A)*A + la.det(A)*I
print(result)

[[5.55111512e-17 0.00000000e+00]
 [0.00000000e+00 5.55111512e-17]]
