# MATH 210 Introduction to Mathematical Computing

## October 7, 2019

* Slicing and indexing NumPy arrays
* Definite integrals and Riemann sums

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Slicing and indexing NumPy arrays

Create a 2D array:

In [2]:
M = np.array([[1,2,3],[4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [3]:
type(M)

numpy.ndarray

Access entries using brackets and indices. For example, access the entry at row index 1 and column index 2.

In [4]:
M[1,2]

6

In [5]:
M[0,1]

2

Create a random matrix.

In [6]:
A = np.random.randint(-100,100,(5,7))
print(A)

[[ -3 -45 -68 -58  50 -79 -11]
 [-53 -36 -79 -91  22 -36 -89]
 [-98 -13 -31 -72 -43  57  44]
 [ 91  17 -18 -47 -21 -84 -63]
 [-89 -13  -9  58 -93  83  25]]


Access the entry at row index 2 and column index 3.

In [7]:
A[2,3]

-72

Use the colon to access a slice (ie. subarray). For example, accessing the subarray in column at index 3.

In [8]:
A[:,3]

array([-58, -91, -72, -47,  58])

In [9]:
A[3,:]

array([ 91,  17, -18, -47, -21, -84, -63])

In [10]:
A[2:5,1:4]

array([[-13, -31, -72],
       [ 17, -18, -47],
       [-13,  -9,  58]])

## Definite integrals and Riemann sums

Let's use Riemann sums with right endpoints to approximate

$$
\int_0^1 e^{-x^2} dx
$$

In [11]:
a = 0
b = 1
N = 10
x = np.linspace(a,b,N+1)
x_right = x[1:]
dx = (b - a)/N
y = np.exp(-x_right**2)*dx
I = np.sum(y)
print(I)

0.7146047681903215


In [12]:
y.size

10

Let's write a function called `exp_riemann` which takes 2 input parameters `b` and `N` and returns the right Riemann sum with $N$ subintervals for 

$$
\int_0^b e^{-x^2}dx
$$

Compare our function to the formula

$$
\int_0^{\infty} e^{-x^2} dx = \frac{\sqrt{\pi}}{2}
$$

In [13]:
def exp_riemann(b,N):
    a = 0
    x = np.linspace(a,b,N+1)
    x_right = x[1:]
    dx = (b - a)/N
    y = np.exp(-x_right**2)*dx
    I = np.sum(y)
    return I

In [14]:
exp_riemann(30,2000)

0.878726925452758

In [15]:
np.sqrt(np.pi)/2

0.8862269254527579

Natural question arises: how close is our Riemann sum to the exact value?